#include "platform/PlatformIntegration.h"

#include <QCoreApplication>
#include <QDesktopServices>
#include <QDir>
#include <QSettings>
#include <QString>
#include <QUrl>

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <appmodel.h>
#include <shlwapi.h>

#include <vector>

namespace mervin {

namespace {

constexpr auto kProgId = "MervinPDF.Document";

QString exePath()
{
    return QDir::toNativeSeparators(QCoreApplication::applicationFilePath());
}

QString applicationUserModelId()
{
    UINT32 length = 0;
    if (GetCurrentApplicationUserModelId(&length, nullptr) != ERROR_INSUFFICIENT_BUFFER)
        return {};
    std::vector<wchar_t> id(length);
    if (GetCurrentApplicationUserModelId(&length, id.data()) != ERROR_SUCCESS)
        return {};
    return QString::fromWCharArray(id.data());
}

} // namespace

bool PlatformIntegration::hasPackageIdentity()
{
    UINT32 length = 0;
    // An unexpected query failure must not enable MSI updates or registry writes
    // in a packaged process. NO_PACKAGE is the documented unpackaged result.
    return GetCurrentPackageFullName(&length, nullptr) != APPMODEL_ERROR_NO_PACKAGE;
}

bool PlatformIntegration::registerPdfHandlerAndPromptDefault()
{
    if (hasPackageIdentity()) {
        // The MSIX manifest registers .pdf. Windows owns its generated ProgID
        // and package path, which changes with every package version.
        const QString aumid = applicationUserModelId();
        const QString uri = aumid.isEmpty()
            ? QStringLiteral("ms-settings:defaultapps")
            : QStringLiteral("ms-settings:defaultapps?registeredAUMID=%1")
                  .arg(QString::fromUtf8(QUrl::toPercentEncoding(aumid)));
        return QDesktopServices::openUrl(QUrl(uri));
    }

    const QString exe = exePath();
    const QString openCmd = QStringLiteral("\"%1\" \"%2\"").arg(exe, QStringLiteral("%1"));

    // ProgID: how to open a Mervin-associated document.
    {
        QSettings progid(
            QStringLiteral("HKEY_CURRENT_USER\\Software\\Classes\\%1").arg(QLatin1String(kProgId)),
            QSettings::NativeFormat);
        // The file type name Windows shows. It outlives any UI language change in
        // the registry, so it stays English rather than translated.
        progid.setValue(QStringLiteral("."), QStringLiteral("PDF Document"));
        progid.setValue(QStringLiteral("shell/open/command/."), openCmd);
        progid.setValue(QStringLiteral("DefaultIcon/."), QStringLiteral("\"%1\",0").arg(exe));
        if (progid.status() != QSettings::NoError)
            return false;
    }

    // Offer the ProgID as an option for .pdf (does not steal the default).
    {
        QSettings assoc(
            QStringLiteral("HKEY_CURRENT_USER\\Software\\Classes\\.pdf\\OpenWithProgids"),
            QSettings::NativeFormat);
        assoc.setValue(QLatin1String(kProgId), QString());
    }

    // Application capabilities + RegisteredApplications, so Mervin shows up in
    // Settings -> Default Apps as a .pdf handler.
    {
        QSettings caps(QStringLiteral("HKEY_CURRENT_USER\\Software\\MervinPDF\\Capabilities"),
                       QSettings::NativeFormat);
        caps.setValue(QStringLiteral("ApplicationName"), QStringLiteral("Mervin PDF"));
        // Shown in Default Apps. It outlives any UI language change in the
        // registry, so it stays English rather than translated.
        caps.setValue(QStringLiteral("ApplicationDescription"),
                      QStringLiteral("Lightweight PDF reader"));
        // Icon shown in Settings -> Default Apps and the "open with" picker;
        // index 0 is the icon embedded in the exe (see resources/icons).
        caps.setValue(QStringLiteral("ApplicationIcon"), QStringLiteral("\"%1\",0").arg(exe));
        caps.setValue(QStringLiteral("FileAssociations/.pdf"), QLatin1String(kProgId));
    }
    {
        QSettings reg(QStringLiteral("HKEY_CURRENT_USER\\Software\\RegisteredApplications"),
                      QSettings::NativeFormat);
        reg.setValue(QStringLiteral("MervinPDF"),
                     QStringLiteral("Software\\MervinPDF\\Capabilities"));
    }

    // Open Default Apps for user confirmation. Supported Windows 11 builds deep-link using the
    // HKCU RegisteredApplications name; older builds show the app list.
    const QString deepLink = QStringLiteral("ms-settings:defaultapps?registeredAppUser=%1")
                                 .arg(QString::fromUtf8(
                                     QUrl::toPercentEncoding(QStringLiteral("MervinPDF"))));
    QDesktopServices::openUrl(QUrl(deepLink));
    return true;
}

bool PlatformIntegration::isDefaultPdfHandler()
{
    if (hasPackageIdentity()) {
        const QString aumid = applicationUserModelId();
        if (aumid.isEmpty())
            return false;
        // ASSOCSTR_APPID resolves the user's effective default. MSIX ProgIDs
        // are generated by Windows and must not be guessed from the manifest.
        DWORD length = 0;
        if (AssocQueryStringW(ASSOCF_NONE, ASSOCSTR_APPID, L".pdf", nullptr, nullptr, &length)
            != S_FALSE)
            return false;
        std::vector<wchar_t> associatedId(length);
        if (AssocQueryStringW(ASSOCF_NONE, ASSOCSTR_APPID, L".pdf", nullptr,
                              associatedId.data(), &length) != S_OK)
            return false;
        return aumid.compare(QString::fromWCharArray(associatedId.data()), Qt::CaseInsensitive) == 0;
    }

    // Windows records the user's chosen default for an extension under
    // FileExts\<ext>\UserChoice as the ProgId value (set via Settings -> Default
    // Apps or the "Open with" dialog). If it names our ProgID, Mervin is the
    // current default. Missing key / different ProgID -> not the default.
    QSettings userChoice(
        QStringLiteral("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion"
                       "\\Explorer\\FileExts\\.pdf\\UserChoice"),
        QSettings::NativeFormat);
    return userChoice.value(QStringLiteral("ProgId"))
               .toString()
               .compare(QLatin1String(kProgId), Qt::CaseInsensitive)
           == 0;
}

} // namespace mervin
